spring:
  application:
    name: PAYMENT-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: product_usr
    password: product_pwd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:9296
server:
  port: 8081
  servlet:
    context-path: /payment
